ALTER SESSION SET USE_CACHED_RESULT = FALSE;

SELECT 
    TIPO_ACCIDENTE,
    ANIO,
    COUNT(*) AS TOTAL
FROM DDS.FACT_INCIDENTES
WHERE ANIO = 2020
  AND GRAVEDAD_ACCIDENTE = 'CON MUERTOS'
GROUP BY TIPO_ACCIDENTE, ANIO
ORDER BY TOTAL DESC;

--after applying cluster by
ALTER TABLE DDS.FACT_INCIDENTES
    CLUSTER BY (ANIO, GRAVEDAD_ACCIDENTE);

-- validate status of clustering
SELECT SYSTEM$CLUSTERING_INFORMATION('DDS.FACT_INCIDENTES');


ALTER SESSION SET USE_CACHED_RESULT = FALSE;

SELECT 
    TIPO_ACCIDENTE,
    ANIO,
    COUNT(*) AS TOTAL
FROM DDS.FACT_INCIDENTES
WHERE ANIO = 2020
  AND GRAVEDAD_ACCIDENTE = 'CON MUERTOS'
GROUP BY TIPO_ACCIDENTE, ANIO
ORDER BY TOTAL DESC;


