--Dynamic Table
CREATE DYNAMIC TABLE INCIDENTES_DIA
    TARGET_LAG = '15 minutes'
    WAREHOUSE = COMPUTE_WH
AS
SELECT count(*) AS TOTAL_INCIDENTES, gravedad_accidente,  barrio, tipo_accidente, anio, mes, dia
FROM DDS.FACT_INCIDENTES
GROUP BY  gravedad_accidente, barrio, tipo_accidente, anio, mes, dia
order by 1 desc


SELECT * FROM INCIDENTES_DIA
ORDER BY TOTAL_INCIDENTES DESC
LIMIT 20;

--to see the status of the dynamic table
SHOW DYNAMIC TABLES LIKE 'INCIDENTES_DIA';

--STREAMS , TASK 

--create stream table to capture changes in the FACT_INCIDENTES table
CREATE OR REPLACE STREAM STR_FACT_INCIDENTES
    ON TABLE DDS.FACT_INCIDENTES
    APPEND_ONLY = TRUE;

---check how many records have been captured in the stream
 SELECT * FROM STR_FACT_INCIDENTES;

 --insert new record into the FACT_INCIDENTES table
 INSERT INTO DDS.FACT_INCIDENTES 
    (NRO_RADICADO, FECHA, ANIO, MES, DIA, DIA_SEMANA, 
     TIPO_DIA, BARRIO, TIPO_ACCIDENTE, GRAVEDAD_ACCIDENTE)
VALUES
    (9999001, '2024-03-15', 2024, 3, 15, '5', 
     'HABIL', 'LAURELES', 'CHOQUE', 'CON HERIDOS'),
    (9999002, '2024-03-15', 2024, 3, 15, '5', 
     'HABIL', 'BELEN', 'ATROPELLO', 'CON MUERTOS'),
    (9999003, '2024-03-15', 2024, 3, 15, '5', 
     'HABIL', 'ROBLEDO', 'CHOQUE', 'SOLO DAÑOS');

     --validiate that the new records have been captured in the stream
 SELECT * FROM STR_FACT_INCIDENTES;


 --TASK 
CREATE OR REPLACE TASK TASK_ACTUALIZAR_RESUMEN
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('STR_FACT_INCIDENTES')
AS
INSERT INTO DDS.INCIDENTES_DIA (FECHA, BARRIO, TIPO_ACCIDENTE, ANIO, MES, DIA, TOTAL_INCIDENTES)
    SELECT 
        FECHA, BARRIO, TIPO_ACCIDENTE, ANIO, MES, DIA,
        COUNT(*) AS TOTAL_INCIDENTES
    FROM STR_FACT_INCIDENTES
    WHERE METADATA$ACTION = 'INSERT'
    GROUP BY FECHA, BARRIO, TIPO_ACCIDENTE, ANIO, MES, DIA;

--activate the task
ALTER TASK TASK_ACTUALIZAR_RESUMEN RESUME;

--validate the status 
SHOW TASKS LIKE 'TASK_ACTUALIZAR_RESUMEN';




--validate specific information 

-- see the table at a specific query id 
SELECT * FROM FACT_INCIDENTES
BEFORE (STATEMENT => '01c4b343-0205-b470-000d-ee2200082136');



--recover data information from a specific point in time
SELECT COUNT(*) FROM DDS.FACT_INCIDENTES; --79537
SELECT COUNT(*) FROM DDS.FACT_INCIDENTES WHERE ANIO = 2020; --4640
DELETE FROM DDS.FACT_INCIDENTES WHERE ANIO = 2020;--4640

CREATE OR REPLACE TABLE DDS.FACT_INCIDENTES AS
    SELECT * FROM DDS.FACT_INCIDENTES
    BEFORE (STATEMENT => '01c4b343-0205-b46f-000d-ee22000830fe');


--clone table
CREATE TABLE DDS.FACT_INCIDENTES_DEV 
    CLONE DDS.FACT_INCIDENTES;
